name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Backend: install & build
        working-directory: backend
        run: |
          npm ci || true
          npm run build || true
      - name: Frontend: install & build
        working-directory: frontend
        run: |
          npm ci || true
          npm run build || true
